<?php
/**
 * Created by PhpStorm.
 * User: zhanghongbo
 * Date: 17/11/2
 * Time: 上午11:37
 */

namespace backend\controllers;

use yii\web\Controller;

class BaseController extends Controller
{
    public $redis;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(\Yii::$app->params['UseRedis']){
            $this->redis = \Yii::$app->redis;
        }
    }

    public function view($view,$data=[]){
        $this->render($view,$data);
    }

    /**
     * 返回layui框架table需要的数据结构
     * @param $tableData
     *
     * @return string
     */
    public function tableDataHeader($tableData){
        $data = ['code'=>0,'msg'=>'','count'=>100,'data'=>$tableData];
        return json_encode($data);
    }
}