<?php

/**
 *
 */
namespace api\Modules\v2;

use yii\base\BootstrapInterface;
use yii\base\Module as BaseModule;

class Module extends BaseModule implements BootstrapInterface {

    public $controllerNamespace = 'api\Modules\v2\Controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function bootstrap($app)
    {
        $app->urlManager->addRules([
            [
                'class' => 'yii\rest\UrlRule',
                'controller' => ['v1/order'],
                'extraPatterns' => [

                ]
            ],
        ]);
    }
}